version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./data:/app/data
    depends_on:
      - ollama
    networks:
      - inksight_network

  frontend:
    build:
      context: .
      dockerfile: app/Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - inksight_network

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - inksight_network

volumes:
  ollama_data:

networks:
  inksight_network: